### ISSUE TITLE
Interesante trabajo

### ISSUE THREAD

**Issue by carloslfu** [ddazal/pickly#1]
Hola, interesante proyecto, podrian tomar algunas ideas de lo desarrollado por Carlos Pereira en [Ardublockly](https://github.com/carlosperate/ardublockly) para arduino. Tambien seria genial poder probarlo online. Un saludo.

**Comment by ddazal** [comment]
Hola @carloslfu muchas gracias. Seguimos de cerca el proyecto que mencionas, básicamente inspiro el que estamos desarrollando y esperamos hacer deploy dentro de mes y medio o dos meses. Estaremos avisando, saludos :)
